### ISSUE TITLE
Both .py files hang

### ISSUE THREAD

**Issue by trevinwong** [gizemdal/mpm#1]
Hi, sorry, this isn't a true issue but I didn't know how to reach the author in any other way. I'm attempting to do something similar (implement the snow simulation paper using Taichi) and I thought this repo would be a great jumping off point. 

Unfortunately, I can't seem to run either of the .py files. Would you mind posting your version information or anything that might help me to run them? Here's my version information:

- **OS:** Windows 10
- **GPU:** NVIDIA RTX 2060 SUPER.
- **Taichi:** 0.8.6
- **llvm:** 10.0.0
- **Python:** 3.8.10
- **numpy:** 1.21.2

**Comment by gizemdal** [comment]
Hi, thanks for reaching out. Here are the versions I used to run the py scripts:

- OS: Windows 10
- GPU: NVIDIA GeForce GTX 1060. I have the Acer Predator Helios 300 gaming laptop if you'd like to compare the other specs.
- Taichi: 0.7.10
- llvm: 10.0.0
- Python: 3.8.0
- numpy: 1.19.3
